export const technologies = [
	{ id: 1, name: "JavaScript", category: "Front-end" },
	{ id: 2, name: "TypeScript", category: "Front-end" },
	{ id: 3, name: "React.js", category: "Front-end" },
	{ id: 4, name: "Angular", category: "Front-end" },
	{ id: 5, name: "Vue.js", category: "Front-end" },
	{ id: 6, name: "Svelte", category: "Front-end" },
	{ id: 7, name: "Ember.js", category: "Front-end" },
	{ id: 8, name: "Backbone.js", category: "Front-end" },
	{ id: 9, name: "Alpine.js", category: "Front-end" },
	{ id: 10, name: "Riot.js", category: "Front-end" },
	{ id: 11, name: "Hyperapp", category: "Front-end" },
	{ id: 12, name: "Inferno", category: "Front-end" },
	{ id: 13, name: "Marko", category: "Front-end" },
	{ id: 14, name: "Solid.js", category: "Front-end" },
	{ id: 15, name: "Webpack", category: "Front-end" },
	{ id: 16, name: "Parcel", category: "Front-end" },
	{ id: 17, name: "Rollup", category: "Front-end" },
	{ id: 18, name: "Snowpack", category: "Front-end" },
	{ id: 19, name: "Babel", category: "Front-end" },
	{ id: 20, name: "Material-UI", category: "Front-end" },
	{ id: 21, name: "Ant Design", category: "Front-end" },
	{ id: 22, name: "Bootstrap", category: "Front-end" },
	{ id: 23, name: "Tailwind CSS", category: "Front-end" },
	{ id: 24, name: "Bulma", category: "Front-end" },
	{ id: 25, name: "Semantic UI", category: "Front-end" },
	{ id: 26, name: "Foundation", category: "Front-end" },
	{ id: 27, name: "Chakra UI", category: "Front-end" },
	{ id: 28, name: "Redux", category: "Front-end" },
	{ id: 29, name: "MobX", category: "Front-end" },
	{ id: 30, name: "Recoil", category: "Front-end" },
	{ id: 31, name: "Zustand", category: "Front-end" },
	{ id: 32, name: "Vuex (Vue.js)", category: "Front-end" },
	{ id: 33, name: "NgRx (Angular)", category: "Front-end" },
	{ id: 34, name: "Akita", category: "Front-end" },
	{ id: 35, name: "Effector", category: "Front-end" },
	{ id: 36, name: "React Router", category: "Front-end" },
	{ id: 37, name: "Vue Router", category: "Front-end" },
	{ id: 38, name: "Angular Router", category: "Front-end" },
	{ id: 39, name: "Reach Router", category: "Front-end" },
	{ id: 40, name: "Next.js", category: "Front-end" },
	{ id: 41, name: "Jest", category: "Front-end" },
	{ id: 42, name: "Mocha", category: "Front-end" },
	{ id: 43, name: "Jasmine", category: "Front-end" },
	{ id: 44, name: "Cypress", category: "Front-end" },
	{ id: 45, name: "TestCafe", category: "Front-end" },
	{ id: 46, name: "Puppeteer", category: "Front-end" },
	{ id: 47, name: "Enzyme", category: "Front-end" },
	{ id: 48, name: "Ava", category: "Front-end" },
	{ id: 49, name: "Redux Toolkit", category: "Front-end" },
	{ id: 50, name: "Redux-Saga", category: "Front-end" },
	{ id: 51, name: "Redux-Observable", category: "Front-end" },
	{ id: 52, name: "ESLint", category: "Front-end" },
	{ id: 53, name: "Prettier", category: "Front-end" },
	{ id: 54, name: "Husky", category: "Front-end" },
	{ id: 55, name: "lint-staged", category: "Front-end" },
	{ id: 56, name: "Visual Studio Code", category: "Front-end" },
	{ id: 57, name: "Atom", category: "Front-end" },
	{ id: 58, name: "Sublime Text", category: "Front-end" },
	{ id: 59, name: "Express.js", category: "Back-end" },
	{ id: 60, name: "Koa", category: "Back-end" },
	{ id: 61, name: "Nest.js", category: "Back-end" },
	{ id: 62, name: "Fastify", category: "Back-end" },
	{ id: 63, name: "Hapi.js", category: "Back-end" },
	{ id: 64, name: "AdonisJS", category: "Back-end" },
	{ id: 65, name: "MongoDB", category: "Banco de Dados" },
	{ id: 66, name: "PostgreSQL", category: "Banco de Dados" },
	{ id: 67, name: "MySQL", category: "Banco de Dados" },
	{ id: 68, name: "SQLite", category: "Banco de Dados" },
	{ id: 69, name: "Redis", category: "Banco de Dados" },
	{ id: 70, name: "Firebase Realtime Database", category: "Banco de Dados" },
	{ id: 71, name: "CouchDB", category: "Banco de Dados" },
	{ id: 72, name: "Cassandra", category: "Banco de Dados" },
	{ id: 73, name: "DynamoDB", category: "Banco de Dados" },
	{ id: 74, name: "Firebase Authentication", category: "Banco de Dados" },
	{ id: 75, name: "Auth0", category: "Back-end" },
	{ id: 76, name: "Passport.js", category: "Back-end" },
	{ id: 77, name: "Keycloak", category: "Back-end" },
	{ id: 78, name: "Okta", category: "Back-end" },
	{ id: 79, name: "Apollo Client e Server", category: "Back-end" },
	{ id: 80, name: "Relay", category: "Back-end" },
	{ id: 81, name: "Prisma", category: "Back-end" },
	{ id: 82, name: "Hasura", category: "Back-end" },
	{ id: 83, name: "GitHub Actions", category: "Back-end" },
	{ id: 84, name: "Jenkins", category: "Back-end" },
	{ id: 85, name: "Travis CI", category: "Back-end" },
	{ id: 86, name: "CircleCI", category: "Back-end" },
	{ id: 87, name: "GitLab CI/CD", category: "Back-end" },
	{ id: 88, name: "Bitbucket Pipelines", category: "Back-end" },
	{ id: 89, name: "Docker", category: "DevOps" },
	{ id: 90, name: "Kubernetes", category: "DevOps" },
	{ id: 91, name: "Terraform", category: "DevOps" },
	{ id: 92, name: "Ansible", category: "DevOps" },
	{ id: 93, name: "Chef", category: "DevOps" },
	{ id: 94, name: "Puppet", category: "DevOps" },
	{ id: 95, name: "Sentry", category: "DevOps" },
	{ id: 96, name: "New Relic", category: "Back-end" },
	{ id: 97, name: "Datadog", category: "Back-end" },
	{
		id: 98,
		name: "ELK Stack (Elasticsearch, Logstash, Kibana)",
		category: "Back-end",
	},
	{ id: 99, name: "Prometheus", category: "Back-end" },
	{ id: 100, name: "Netlify", category: "Back-end" },
	{ id: 101, name: "Vercel", category: "Back-end" },
	{ id: 102, name: "Heroku", category: "Back-end" },
	{ id: 103, name: "AWS", category: "Back-end" },
	{ id: 104, name: "Microsoft Azure", category: "Back-end" },
	{ id: 105, name: "Google Cloud Platform", category: "Back-end" },
	{ id: 106, name: "DigitalOcean", category: "Back-end" },
	{ id: 107, name: "Firebase Hosting", category: "Back-end" },
	{ id: 108, name: "React Native", category: "Mobile" },
	{ id: 109, name: "Expo", category: "Mobile" },
	{ id: 110, name: "Flutter (Dart)", category: "Mobile" },
	{ id: 111, name: "Ionic", category: "Mobile" },
	{ id: 112, name: "Socket.io", category: "Back-end" },
	{ id: 113, name: "WebSocket API", category: "Back-end" },
	{ id: 114, name: "Pusher", category: "Back-end" },
	{ id: 115, name: "AWS Lambda", category: "Back-end" },
	{ id: 116, name: "Azure Functions", category: "Back-end" },
	{ id: 117, name: "Netlify Functions", category: "Back-end" },
	{ id: 118, name: "Firebase Functions", category: "Back-end" },
	{ id: 119, name: "Git", category: "Back-end" },
	{ id: 120, name: "GitHub", category: "Back-end" },
	{ id: 121, name: "GitLab", category: "Back-end" },
	{ id: 122, name: "Bitbucket", category: "Back-end" },
	{ id: 123, name: "SVN (Subversion)", category: "Back-end" },
	{ id: 124, name: "Docker", category: "Back-end" },
	{ id: 125, name: "Kubernetes", category: "Back-end" },
	{ id: 126, name: "Terraform", category: "Back-end" },
	{ id: 127, name: "Ansible", category: "Back-end" },
	{ id: 128, name: "Chef", category: "Back-end" },
	{ id: 129, name: "Puppet", category: "Back-end" },
	{ id: 130, name: "Sentry", category: "Back-end" },
	{ id: 131, name: "New Relic", category: "Back-end" },
	{ id: 132, name: "Datadog", category: "Back-end" },
	{
		id: 133,
		name: "ELK Stack (Elasticsearch, Logstash, Kibana)",
		category: "Back-end",
	},
	{ id: 134, name: "Prometheus", category: "Back-end" },
];
